# -*- coding: utf-8 -*-
"""forecasting_RQ3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iA1kEY89RUNXEDvIIlyPLPgMTjT7tVb

CHECK FOR LINEARITY
"""

import pandas as pd, numpy as np, seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

from google.colab import files
uploaded = files.upload()

df_paip = pd.read_csv("PAIP_final.csv")

monthly = (df_paip.groupby("t")
             .agg(nrw=("NRW_m3", "sum"), prod=("Production_m3", "sum")))
monthly["nrw_pct"] = monthly["nrw"] / monthly["prod"] * 100

df = pd.DataFrame({"Month": np.arange(1, 37),
                   "NRW_pct": monthly["nrw_pct"].values})

# Pearson correlation — is there a linear relationship with time?
r_val, p_val = stats.pearsonr(df["Month"], df["NRW_pct"])
print(f"Pearson r: {r_val:.4f}   p-value: {p_val:.3e}   R²: {r_val**2:.4f}")

# Does adding curvature improve the fit?
lin  = np.polyfit(df.Month, df.NRW_pct, 1)
quad = np.polyfit(df.Month, df.NRW_pct, 2)
r2 = lambda p: 1 - np.sum((df.NRW_pct - np.polyval(p, df.Month))**2) \
                 / np.sum((df.NRW_pct - df.NRW_pct.mean())**2)
print(f"Linear R²    {r2(lin):.4f}")
print(f"Quadratic R² {r2(quad):.4f}  (curvature {quad[0]:+.6f})")
print("-> no improvement from curvature: trend is linear")

# Scatter with fitted line
plt.figure(figsize=(9, 5))
sns.regplot(x="Month", y="NRW_pct", data=df, line_kws={"color": "red"})
plt.title(f"Linear trend check (r = {r_val:.3f}, R² = {r_val**2:.3f})")
plt.xlabel("Month index (Jan 2023 = 1)")
plt.ylabel("State NRW (%)")
plt.grid(alpha=.3)
plt.show()

"""FORECASTING"""

# setup
!pip install statsmodels --quiet

import warnings, itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import Holt
from statsmodels.tsa.statespace.sarimax import SARIMAX

warnings.filterwarnings("ignore")

TARGET = 25.0   # national NRW target (%)
H      = 60     # forecast horizon: Jan 2026 -> Dec 2030

# load data
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("PAIP_final.csv")
print(df.shape, "|", df.Plant_Name.nunique(), "plants")

# build the state-level monthly series
# Volume-weighted: sum volumes then divide.
# Averaging plant percentages would weight a small plant equally.
# with a large one, and would not reconcile to the state total.

monthly = (df.groupby("t")
             .agg(nrw=("NRW_m3", "sum"), prod=("Production_m3", "sum")))
monthly["nrw_pct"] = monthly["nrw"] / monthly["prod"] * 100

y = monthly["nrw_pct"].values
dates = pd.period_range("2023-01", periods=len(y), freq="M")
assert len(y) == 36

train, test = y[:30], y[30:]        # chronological split, no shuffling

def metrics(pred, actual):
    e = np.asarray(pred) - np.asarray(actual)
    return (np.mean(np.abs(e)),
            np.sqrt(np.mean(e**2)),
            np.mean(np.abs(e / np.asarray(actual))) * 100)

print(f"Series: {y.min():.2f}% to {y.max():.2f}%")

# =============================================================
# MODEL 1 — Linear trend (OLS on time index)
# Assumes: NRW declines at a constant rate throughout.
# Role: interpretable baseline. Slope = pp of NRW reduced per month.
# =============================================================
# ---- CELL 4 --------------------------------------------------
coef_lin = np.polyfit(np.arange(30), train, 1)
pred_lin = np.polyval(coef_lin, np.arange(30, 36))

print(f"Slope: {coef_lin[0]*12:+.3f} pp per year")
print("MAE %.3f  RMSE %.3f  MAPE %.2f%%" % metrics(pred_lin, test))

# full-sample refit for the 2030 forecast
coef_lin_full = np.polyfit(np.arange(36), y, 1)
fc_lin = np.polyval(coef_lin_full, np.arange(36, 36 + H))

# =============================================================
# MODEL 2 — Holt undamped (double exponential smoothing)
# Assumes: level and trend both update; trend continues at full strength indefinitely.
# =============================================================

holt_u = Holt(train).fit(optimized=True)
pred_hu = holt_u.forecast(6)

print(f"alpha={holt_u.params['smoothing_level']:.3f}  "
      f"beta={holt_u.params['smoothing_trend']:.3f}")
print("MAE %.3f  RMSE %.3f  MAPE %.2f%%" % metrics(pred_hu, test))

final_hu = Holt(y).fit(optimized=True)
fc_hu = final_hu.forecast(H)

sim_hu = np.asarray(final_hu.simulate(H, repetitions=2000,
                                      error="add", random_state=42))
hu_lo80, hu_hi80 = np.percentile(sim_hu, [10, 90], axis=1)

print(f"\nDec 2030 point forecast: {fc_hu[-1]:.2f}%")
print(f"Dec 2030 80% interval:   {hu_lo80[-1]:.1f}% to {hu_hi80[-1]:.1f}%")
print("^ NRW cannot be negative or exceed 100%. The unrestrained trend")
print("  compounds over 60 steps and the model leaves its valid range.")

# =============================================================
# MODEL 3 — Holt damped
# Assumes: trend decays by factor phi each step forward.
# Rationale: NRW reduction decelerates — the easy leaks are found first, the remainder are progressively harder.
# =============================================================

holt_d = Holt(train, damped_trend=True).fit(optimized=True)
pred_hd = holt_d.forecast(6)

print(f"alpha={holt_d.params['smoothing_level']:.3f}  "
      f"beta={holt_d.params['smoothing_trend']:.3f}  "
      f"phi={holt_d.params['damping_trend']:.3f}")
print("MAE %.3f  RMSE %.3f  MAPE %.2f%%" % metrics(pred_hd, test))

final_hd = Holt(y, damped_trend=True).fit(optimized=True)
fc_hd = final_hd.forecast(H)

sim_hd = np.asarray(final_hd.simulate(H, repetitions=2000,
                                      error="add", random_state=42))
hd_lo80, hd_hi80 = np.percentile(sim_hd, [10, 90], axis=1)
hd_lo95, hd_hi95 = np.percentile(sim_hd, [2.5, 97.5], axis=1)

print(f"\nDec 2030 point forecast: {fc_hd[-1]:.2f}%")
print(f"Dec 2030 80% interval:   {hd_lo80[-1]:.1f}% to {hd_hi80[-1]:.1f}%")
print("^ bounded and physically meaningful")

# =============================================================
# MODEL 4 — SARIMA
# Assumes: values depend on their own recent history;
# Test for an annual seasonal cycle (monsoon -> rainfall -> NRW?).
# Order selected by AIC on TRAIN only, never on the test set.
# =============================================================

cands = []
for p, d_, q in itertools.product([0, 1, 2], [0, 1], [0, 1, 2]):
    try:
        m = SARIMAX(train, order=(p, d_, q),
                    trend="c" if d_ == 0 else "n").fit(disp=False)
        cands.append(((p, d_, q), m.aic))
    except Exception:
        pass

best_order = min(cands, key=lambda c: c[1])[0]
print(f"Best order by AIC: SARIMA{best_order}")

sar = SARIMAX(train, order=best_order,
              trend="c" if best_order[1] == 0 else "n").fit(disp=False)
pred_sar = sar.forecast(6)
print("MAE %.3f  RMSE %.3f  MAPE %.2f%%" % metrics(pred_sar, test))

sar_full = SARIMAX(y, order=best_order,
                   trend="c" if best_order[1] == 0 else "n").fit(disp=False)
fc_sar = sar_full.forecast(H)

# Seasonality check — 36 months gives only 3 annual cycles
try:
    seas = SARIMAX(train, order=(0, 1, 1),
                   seasonal_order=(1, 0, 0, 12)).fit(disp=False)
    print(f"\nWith seasonal term: MAE {metrics(seas.forecast(6), test)[0]:.3f}")
    print("Seasonal term does not improve accuracy -> no exploitable")
    print("annual cycle. NRW is driven by network condition, not weather.")
except Exception as e:
    print("seasonal fit failed:", e)

# =============================================================
# COMPARISON TABLE
# =============================================================

comparison = pd.DataFrame({
    "Linear trend (OLS on time)": metrics(pred_lin, test),
    "Holt's undamped":              metrics(pred_hu,  test),
    "Holt's damped":                metrics(pred_hd,  test),
    f"SARIMA{best_order}":        metrics(pred_sar, test),
}, index=["MAE", "RMSE", "MAPE (%)"]).T.round(3).sort_values("MAE")

print("Held-out performance (final 6 months)\n")
print(comparison.to_string())
print("\nNote: the two Holt variants differ by 0.008 MAE — noise over six")
print("points. The 6-month test CANNOT separate them. Selection therefore")
print("rests on the long-horizon diagnostic in Cells 5 and 6.")

# =============================================================
# CHART 1 — four models compared (methodology section)
# =============================================================

x_h, x_f = np.arange(36), np.arange(36, 36 + H)

fig, ax = plt.subplots(figsize=(12, 6))

ax.plot(x_h, y, color="#1F4E79", lw=2.4, label="Actual (2023–2025)")

for fc, lab, col in [
    (fc_lin, "Linear trend",           "#6A4C93"),
    (fc_hu,  "Holt's undamped",          "#C1121F"),
    (fc_hd,  "Holt's damped",            "#0F7C6E"),
    (fc_sar, f"SARIMA{best_order}",    "#B5651D"),
]:
    ax.plot(x_f, fc, color=col, lw=2.2, ls=":", label=lab)

ax.axhline(TARGET, color="#4A7A4E", lw=1.2)
ax.text(1, TARGET + .45, f"National target {TARGET:.0f}%",
        color="#4A7A4E", fontsize=10, fontweight="bold")

ax.axvline(35.5, color="grey", lw=.8, alpha=.5)
ax.text(36.5, ax.get_ylim()[0] + .3, "forecast begins",
        fontsize=9, color="grey")

ticks = list(range(0, 36 + H, 12))
ax.set_xticks(ticks)
ax.set_xticklabels([str(2023 + t // 12) for t in ticks])

ax.set_ylabel("Non-Revenue Water (%)")
ax.set_xlabel("Year")
ax.set_title("Model Comparison: Four Forecasts of Pahang NRW (%) to 2030",
             fontsize=13, fontweight="bold", loc="left")

ax.legend(frameon=False, loc="upper right", ncol=1, fontsize=10)

ax.grid(alpha=.22, ls="--")
for s in ["top", "right"]:
    ax.spines[s].set_visible(False)

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=200, bbox_inches="tight")
plt.show()

# NOTE: these are four fitted MODELS, not best/expected/worst-case
# SCENARIOS. Caption the chart accordingly — a multi-line forecast
# chart is often misread as a scenario fan.

# =============================================================
# CHART 2 — holt's damped with prediction intervals
# =============================================================

fig, ax = plt.subplots(figsize=(12, 6))

ax.fill_between(x_f, hd_lo95, hd_hi95, color="#c8d8e8", alpha=.45,
                label="95% prediction interval")
ax.fill_between(x_f, hd_lo80, hd_hi80, color="#8fb4d4", alpha=.55,
                label="80% prediction interval")

ax.plot(x_h, y, color="#1f4e79", lw=2.2, label="Actual (2023–2025)")
ax.plot(x_f, fc_hd, color="#d1495b", lw=2.2, ls="--",
        label="Forecast (Holt's damped)")

ax.axhline(TARGET, color="#2e7d32", lw=1.5, ls=":")
ax.text(1, TARGET + .6, f"National target {TARGET:.0f}%",
        color="#2e7d32", fontsize=10, fontweight="bold")
ax.axvline(35.5, color="grey", lw=.8, alpha=.6)

ax.set_xticks(ticks)
ax.set_xticklabels([str(2023 + t // 12) for t in ticks])
ax.set_ylabel("Non-Revenue Water (%)")
ax.set_xlabel("Year")

ax.set_title("Pahang NRW (%): Actual and Forecast to 2030",
             fontsize=13, fontweight="bold", loc="left", pad=22)
ax.text(0, 1.015, "Holt's damped method",
        transform=ax.transAxes, fontsize=10, color="#5A5A5A",
        style="italic", va="bottom")

ax.legend(frameon=False, loc="lower left")
ax.grid(alpha=.25, ls="--")
ax.set_ylim(10, 45)
for s in ["top", "right"]:
    ax.spines[s].set_visible(False)
plt.tight_layout()
plt.savefig("nrw_forecast.png", dpi=200, bbox_inches="tight")
plt.show()

hit = np.where(fc_hd <= TARGET)[0]
fut = pd.period_range("2026-01", periods=H, freq="M")
print(f"Reaches {TARGET}%: "
      + (f"{fut[hit[0]]}" if len(hit) else "NOT on current trajectory"))

# export
fut = pd.period_range("2026-01", periods=H, freq="M")

out = pd.concat([
    pd.DataFrame({"date": dates.astype(str), "type": "actual",
                  "nrw_pct": y}),
    pd.DataFrame({"date": fut.astype(str), "type": "forecast",
                  "nrw_pct": fc_hd,
                  "lo80": hd_lo80, "hi80": hd_hi80,
                  "lo95": hd_lo95, "hi95": hd_hi95}),
])
out.to_csv("nrw_forecast.csv", index=False)
print("Exported: nrw_forecast.csv — this is the file the app reads.")