# -*- coding: utf-8 -*-
"""LIPS_Construction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuSrf0FXvxyzGkAuz2JkIpnPjTjN-GXP
"""

# SETUP
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr

W_DEFAULT     = 0.70   # weight on recoverable volume vs ease of repair
ALPHA_DEFAULT = 0.30   # weight on district vulnerability
RECOVERY      = 0.40   # assumed share of physical loss eliminated per repair

# LOAD DATA
from google.colab import files
uploaded = files.upload()

paip = pd.read_csv("PAIP_final.csv")
dosm = pd.read_csv("pahang_district_master_cleaned_data.csv")

print(f"PAIP: {paip.shape[0]:,} rows · {paip.Plant_Name.nunique()} plants "
      f"· {paip.District.nunique()} districts")
print(f"DOSM: {dosm.shape[0]} rows · years {sorted(dosm.year.unique())}")

# =============================================================
# STEP 1 — Recoverable volume
# =============================================================

# Physical loss ONLY. Commercial loss (meter under-registration billing error) needs a metering programme, not a repair crew.

plant = (paip.groupby(["Plant_Name", "District", "Area_Type"])
             .agg(physical_total = ("Physical_Loss_m3", "sum"),
                  nrw_total      = ("NRW_m3", "sum"),
                  production     = ("Production_m3", "sum"),
                  pipe_km        = ("Pipe_Length_km", "mean"),
                  plant_age      = ("Plant_Age_Years", "mean"),
                  bursts         = ("Pipe_Break_Incidents", "sum"),
                  population     = ("Population_Served", "mean"))
             .reset_index())

plant["annual_recoverable"] = plant.physical_total / 3          # V_i
plant["nrw_pct"]            = plant.nrw_total / plant.production * 100
plant["bursts_per_km"]      = plant.bursts / plant.pipe_km      # B_i

V = plant.annual_recoverable
print(f"V ranges {V.min():,.0f} to {V.max():,.0f} m³/yr "
      f"({V.max()/V.min():.0f}-fold spread)")
print(f"State total recoverable: {V.sum()/1e6:.1f}M m³/yr")

# =============================================================
# STEP 2 — Repair difficulty index
# =============================================================

# Three components, min-max normalised, EQUAL weights.
# Equal weighting follows OECD/EC-JRC (2008) for composite
# indicators with no empirical basis for differential weights.

def minmax(s):
    """Normalise a series to [0, 1]."""
    return (s - s.min()) / (s.max() - s.min())

plant["d_pipe"]    = minmax(np.log(plant.pipe_km))     # more network to survey
plant["d_age"]     = minmax(plant.plant_age)           # older = harder works
plant["d_diffuse"] = 1 - minmax(plant.bursts_per_km)   # INVERTED, see below

# Burst rate enters inversely: a plant with frequent, concentrated
# failures has locatable leaks. A plant losing water diffusely across
# a long rural network with few recorded bursts does not.

plant["difficulty"] = (plant.d_pipe + plant.d_age + plant.d_diffuse) / 3

D = plant.difficulty
print(f"D ranges {D.min():.3f} to {D.max():.3f} ({D.max()/D.min():.1f}-fold)")
print(f"\nCompare: V varies {V.max()/V.min():.0f}× but D only {D.max()/D.min():.1f}×")
print("This disparity is why raw values cannot be combined directly.")

# =============================================================
# STEP 3 — Why raw combination fails (diagnostic)
# =============================================================

# Demonstrates the problem the rank transformation solves.

naive = plant.annual_recoverable / (0.5 + plant.difficulty)
rho_naive = spearmanr(naive, plant.annual_recoverable)[0]

print(f"Naive score (V ÷ difficulty) vs raw volume: ρ = {rho_naive:.3f}")
print("The difficulty term is present in the formula but has almost no")
print("effect on the ordering — volume dominates because it varies 163×.")

# =============================================================
# STEP 4 — Rank transformation and LIPS
# =============================================================

# Percentile ranks equalise the dispersion of both components, so the weighting parameter can actually shift the balance between them.

plant["R_volume"] = plant.annual_recoverable.rank(pct=True)   # Eq 3
plant["R_ease"]   = (1 - plant.difficulty).rank(pct=True)     # Eq 4

def compute_lips(df, w):
    return 100 * (w * df.R_volume + (1 - w) * df.R_ease)

plant["LIPS"] = compute_lips(plant, W_DEFAULT)

rho_ranked = spearmanr(plant.LIPS, plant.annual_recoverable)[0]
print(f"LIPS (w={W_DEFAULT}) vs raw volume: ρ = {rho_ranked:.3f}")
print(f"Compare with the naive score's {rho_naive:.3f} — difficulty now matters.\n")

print("Top 10 by LIPS (technical criteria only):")
print(plant.nlargest(10, "LIPS")[
    ["Plant_Name", "District", "annual_recoverable", "nrw_pct",
     "difficulty", "LIPS"]].round(2).to_string(index=False))

# =============================================================
# STEP 5 — Sensitivity to the volume weighting
# =============================================================

# w has no objectively correct value, so report how the queue responds.

volume_top10 = set(plant.nlargest(10, "annual_recoverable").Plant_Name)

rows = []
for w in [0.5, 0.6, 0.7, 0.8, 0.9]:
    L = compute_lips(plant, w)
    top = plant.assign(L=L).nlargest(10, "L")
    rows.append({
        "w": w,
        "Spearman vs volume": round(spearmanr(L, plant.annual_recoverable)[0], 3),
        "Shared with volume top-10": f"{len(set(top.Plant_Name) & volume_top10)} / 10",
        "Recoverable (Mm³/yr)": round(top.annual_recoverable.sum() / 1e6, 1),
    })

sens_w = pd.DataFrame(rows)
print(sens_w.to_string(index=False))
print("\nNote the discontinuity between w=0.6 and w=0.7: the queue converts")
print("from ease-led to volume-led. The default sits just above it.")

# =============================================================
# STEP 6 — District Vulnerability Index   [Equation 6]
# =============================================================

# DVI is a STRUCTURAL district attribute, not a time series, so the 2024 snapshot is used directly.

d24 = dosm[dosm.year == 2024].copy()
d24["DVI"] = (minmax(d24.poverty_relative_pct)          # higher poverty = worse
              + minmax(-d24.income_median_rm)) / 2      # lower income  = worse

print(d24[["district", "poverty_relative_pct", "income_median_rm", "DVI"]]
      .sort_values("DVI", ascending=False).round(3).to_string(index=False))

# PAIP districts are UPPERCASE, DOSM is Title Case
plant["district_key"] = plant.District.str.title()
plant = plant.merge(d24[["district", "DVI"]],
                    left_on="district_key", right_on="district", how="left")
assert plant.DVI.notna().all(), "district join failed — check name casing"
print("\nJoin verified: all 74 plants matched to a district DVI.")

# =============================================================
# STEP 7 — Priority Repair Index
# =============================================================

def compute_pri(df, alpha):
    return df.LIPS * (1 + alpha * df.DVI)

plant["PRI"] = compute_pri(plant, ALPHA_DEFAULT)
plant["rank_LIPS"] = plant.LIPS.rank(ascending=False).astype(int)
plant["rank_PRI"]  = plant.PRI.rank(ascending=False).astype(int)
plant["moved"]     = plant.rank_LIPS - plant.rank_PRI

queue = plant.sort_values("PRI", ascending=False).reset_index(drop=True)

print(f"Top 10 by PRI (α = {ALPHA_DEFAULT}):\n")
print(queue.head(10)[["Plant_Name", "District", "DVI",
                      "rank_LIPS", "rank_PRI", "moved"]].to_string(index=False))

print("\nLargest rank movements:")
print(plant.reindex(plant.moved.abs().nlargest(5).index)[
    ["Plant_Name", "District", "DVI", "rank_LIPS", "rank_PRI", "moved"]
    ].to_string(index=False))

# =============================================================
# STEP 8 — What the community need weighting costs
# =============================================================

# The central trade-off: equity weighting redistributes outcomes, it does not improve them. Quantify the cost rather than embedding it.

ANNUAL_PRODUCTION = 658_300_000   # m³/yr, state total
BASELINE_2030     = 31.73         # % from the damped Holt forecast

rows = []
for alpha in [0.0, 0.1, 0.2, 0.3, 0.5, 1.0]:
    top = plant.assign(P=compute_pri(plant, alpha)).nlargest(10, "P")
    rec = top.annual_recoverable.sum()
    pp  = rec * RECOVERY / ANNUAL_PRODUCTION * 100
    rows.append({
        "alpha": alpha,
        "Recoverable (Mm³/yr)": round(rec / 1e6, 1),
        "Districts": top.District.nunique(),
        "Reduction (pp)": round(pp, 2),
        "2030 NRW (%)": round(BASELINE_2030 - pp, 2),
    })

sens_a = pd.DataFrame(rows)
print(sens_a.to_string(index=False))

drop = (1 - sens_a.loc[3, "Recoverable (Mm³/yr)"]
            / sens_a.loc[0, "Recoverable (Mm³/yr)"]) * 100
print(f"\nAt α = 0.3 the plan recovers {drop:.1f}% less water.")
print("The effect saturates at α = 0.3 — beyond it the queue stops changing.")

# =============================================================
# STEP 9 — Programme size and diminishing returns
# =============================================================

eng = plant.assign(P=plant.LIPS).sort_values("P", ascending=False)

rows, prev = [], 0.0
for N in [5, 10, 15, 20, 25, 30]:
    rec = eng.head(N).annual_recoverable.sum()
    pp  = rec * RECOVERY / ANNUAL_PRODUCTION * 100
    rows.append({
        "Plants": N,
        "Recoverable (Mm³/yr)": round(rec / 1e6, 1),
        "Share of state": f"{rec / plant.annual_recoverable.sum() * 100:.1f}%",
        "Reduction (pp)": round(pp, 2),
        "Marginal (pp)": round(pp - prev, 2),
        "2030 NRW (%)": round(BASELINE_2030 - pp, 2),
    })
    prev = pp

prog = pd.DataFrame(rows)
print(prog.to_string(index=False))
print("\nThe first 10 plants deliver more than the next 15 combined.")
print("Recoverable water is concentrated at the top of the queue, which is")
print("why the ORDER matters as much as the count.")

fig, ax = plt.subplots(figsize=(10, 5.5))

ax.bar(prog.Plants, prog["Marginal (pp)"], width=3.2,
       color="#158AA8", label="Added by this step")
ax.plot(prog.Plants, prog["Reduction (pp)"], color="#B87614",
        marker="o", lw=2.2, label="Cumulative reduction")
ax.axhline(BASELINE_2030 - 25, color="#B83B3B", ls=":", lw=1.4)
ax.text(5.5, BASELINE_2030 - 25 + .12, "gap to 25% target (6.73 pp)",
        color="#B83B3B", fontsize=9, fontweight="bold")

ax.set_xlabel("Plants repaired")
ax.set_ylabel("Reduction in state NRW (percentage points)")
ax.set_title("Diminishing returns to programme size",
             fontsize=13, fontweight="bold", loc="left")
ax.legend(frameon=False)
ax.grid(alpha=.22, ls="--", axis="y")
for s in ["top", "right"]:
    ax.spines[s].set_visible(False)
plt.tight_layout()
plt.savefig("diminishing_returns.png", dpi=200, bbox_inches="tight")
plt.show()

# =============================================================
# STEP 10 — Export
# =============================================================
# ---- CELL 13 -------------------------------------------------
cols = ["Plant_Name", "District", "Area_Type", "annual_recoverable",
        "nrw_pct", "production", "pipe_km", "plant_age", "bursts_per_km",
        "difficulty", "R_volume", "R_ease", "LIPS", "DVI", "PRI",
        "rank_LIPS", "rank_PRI", "moved"]

queue[cols].to_csv("lips_queue.csv", index=False)
sens_w.to_csv("sensitivity_w.csv", index=False)
sens_a.to_csv("sensitivity_alpha.csv", index=False)

print("\nNote: the app recomputes LIPS and PRI live from R_volume, R_ease")
print("and DVI, so the stored LIPS/PRI columns are the defaults only.")

files.download("lips_queue.csv")
files.download("diminishing_returns.png")